const sportsList = [
    "Archery",
    "Badminton",
    "Baseball",
    "Basketball",
    "Boxing",
    "Bowling",
    "Cricket",
    "Cross Country",
    "Cycling",
    "Competitive Cheerleading",
    "Darts",
    "Field Hockey",
    "Figure Skating",
    "Fishing",
    "Football",
    "Gymnastics",
    "Horseback Riding",
    "Ice Hockey",
    "Lacrosse",
    "Martial Arts",
    "Rock Climbing",
    "Rugby",
    "Soccer",
    "Surfing",
    "Swimming & Diving",
    "Tennis",
    "Track & Field",
    "Triathlon",
    "Volleyball",
    "Water Polo",
    "Weightlifting",
    "Wrestling",
  ];

  export default sportsList;